/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interview;

import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {

    static Routes routes;
    static String[] allRoutes;
    static String[] uniqueRoutes;
    static String[] user42Routes;
    static String[] user42StravaKomootRoutes;

    @BeforeClass public static void init(){
        ServiceManager serviceManager = new ServiceManager.Builder()
                .withService("Strava", "interview.StravaService")
                .withService("RWGPS", "interview.RWGPSService")
                .withService("Komoot", "interview.KomootService")
                .build();
        routes = new Routes(serviceManager);
        allRoutes = new String[]{"SRT", "CVT", "Perkiomen", "SRT", "Welsh Mountain", "Oaks to Philly", "CVT", "Perkiomen", "Welsh Mountain"};
        uniqueRoutes = new String[]{"CVT", "Perkiomen", "SRT", "Welsh Mountain", "Oaks to Philly"};
        user42Routes = new String[]{"42SRT", "42CVT", "42Perkiomen", "42SRT42", "42Welsh Mountain42", "42Oaks to Philly42", "CVT42", "Perkiomen42", "Welsh Mountain42"};
        user42StravaKomootRoutes = new String[]{"42SRT", "42CVT", "42Perkiomen", "42SRT42", "42Welsh Mountain42", "42Oaks to Philly42"};
    }

    @Test public void testAllRoutes() {
        String[] result = routes.getAllRoutes().toArray(new String[0]);
        Assert.assertArrayEquals( allRoutes, result );
    }

    @Test public void testUniqueRoutes() {
        String[] result = routes.getUniqueRoutes().toArray(new String[0]);
        Assert.assertArrayEquals( uniqueRoutes, result );
    }

    @Test public void testUserRoutes() {
        String[] result = routes.getUserRoutes("42").toArray(new String[0]);
        Assert.assertArrayEquals( user42Routes, result );
    }
    @Test public void testUserServiceRoutes() {
        String[] services = new String[]{"Strava", "Komoot"};
        String[] result = routes.getUserRoutesByService("42", services).toArray(new String[0]);
        Assert.assertArrayEquals( user42StravaKomootRoutes, result );
    }
}
