version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk

    steps:
      - checkout

      - run:
          name: Build
          command: ./gradlew run

      - run:
          name: Test
          command: ./gradlew clean test