version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Build
          command: ./gradlew run

      - run:
          name: Test
          command: echo "Not implemented" && exit 1