/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interview;

public class App {

    public static void main(String[] args) {

        ServiceManager serviceManager = new ServiceManager.Builder()
                .withService("Strava", "interview.StravaService")
                .withService("RWGPS", "interview.RWGPSService")
                .withService("Komoot", "interview.KomootService")
                .build();
        Routes routes = new Routes(serviceManager);
        Routes.printRoutes(routes.getAllRoutes());
        Routes.printRoutes(routes.getUniqueRoutes());
        Routes.printRoutes(routes.getUserRoutes("42"));
        String[] services = new String[]{"Strava", "Komoot"};
        Routes.printRoutes(routes.getUserRoutesByService("42", services ));
    }
}
